#!/bin/bash

echo

if [[ "_$1" = "_" ]]; then
  echo "Error:  Need argument, 1 or 2."
  echo "  1 - Creates the dir list."
  echo "  2 - Calls blobractor on all vids in list."
  echo "  To export all vids, do:"
  echo "    ./aa 1; ./aa 2"
  echo "  To export only some vids, do the following:"
  echo "    - First do ./aa 1"
  echo "    - Remove unwanted videos from the dir list file."
  echo "    - Do ./aa 2"
  echo
  exit 1

elif [[ "$1" = "1" ]]; then
  prs-stractor --config stractor.config --mode_make_list


elif [[ "$1" = "2" ]]; then
  prs-stractor --config stractor.config --mode_export

else
  echo "Error:  Unrecognized argument."; echo
  exit 1
fi


echo


